<header class="site-header site-header--slim flex-none mb-0 p-0">
    <?= $this->fetch('includes/cloud-nav.phtml') ?>
</header>
<section id="app" class="site-body h-full flex-1 flex flex-col bg-gray-900">
    <exercise-editor next-exercise-link='<?= $nextExerciseLink ?>'
                     :official-solution='<?= $this->json($official_solution ?? null) ?>'
                     :workshop='<?= $this->json($workshop) ?>'
                     :exercise='<?= $this->json($exercise) ?>'>
        <template #problem>
            <?= $problem ?>
        </template>

    </exercise-editor>
</section>
