<header class="site-header site-header--slim">
    <?= $this->fetch('includes/site-nav.phtml') ?>
    <div class="container flex flex-col items-center">
        <h1 class="site-header__title">PHP School Cloud</h1>

        <nav class="flex" aria-label="Breadcrumb">
            <ol class="inline-flex items-center space-x-1 md:space-x-3">
                <li class="inline-flex items-center">
                    <a href="/cloud" class="inline-flex items-center text-sm font-medium text-white hover:text-pink-500">
                        <svg class="w-4 h-4 mr-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z"></path></svg>
                        <?= $workshop->getName() ?>
                    </a>
                </li>
                <li>
                    <div class="flex items-center">
                        <svg class="w-6 h-6 text-pink-500" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
                        <a href="#" class="ml-1 text-sm font-medium text-white hover:text-pink-500 md:ml-2"><?= $exercise->getName() ?></a>
                    </div>
                </li>
            </ol>
        </nav>
    </div>
</header>
    <section id="app" class="site-body flex flex-col bg-gray-900">
        <exercise-editor next-exercise-link='<?= $nextExerciseLink ?>'
                         :official-solution='<?= $this->json($official_solution ?? null) ?>'
                         workshop-code='<?= $workshop->getCode() ?>'
                         exercise-slug='<?= $this->slug($exercise->getName()) ?>'>
            <template #problem>
                <?= $problem ?>
            </template>

        </exercise-editor>
</section>

<script>
    document.addEventListener("DOMContentLoaded", function(event) {

        var editor = ace.edit("editor");
        window.editor = editor;
        editor.setTheme("ace/theme/monokai");
        editor.session.setMode("ace/mode/php");
        editor.setValue('<' + '?php' + "\n");

        editor.session.on('change', function(delta) {
            //nuke the results
            const results = document.getElementById("results");
            results.innerHTML = '';
        });
    });
</script>