<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Event</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <?= $form->openHorizontal(['lg' => [2, 6]])->multipart()->action('/admin/event/create') ?>
                <?= $form->text('Title', 'name')->addClass('required'); ?>
                <?= $form->textArea('Description', 'description')->rows(5)->addClass('required'); ?>
                <?= $form->text('Link', 'link') ?>
                <?= $form->dateTimeLocal('Date', 'date')->addClass('required'); ?>
                <?= $form->textArea('Venue', 'venue')->rows(5)->addClass('required'); ?>
                <?= $form->file('Poster', 'poster'); ?>
                <?= $form->submit('Submit'); ?>
                <?= $form->close(); ?>
            </div>
        </div>
    </div>
</div>