<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Event</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br>
                <form enctype="multipart/form-data" id="create-event" class="form-horizontal form-label-left" method="POST" action="/admin/event/create">

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="title">Title <span class="required">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" id="title" name="title" required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description">Description <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" id="description" name="description" required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="date" class="control-label col-md-3 col-sm-3 col-xs-12">Date</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input id="date" name="date" class="form-control col-md-7 col-xs-12" type="datetime-local" required="required">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="venue" class="control-label col-md-3 col-sm-3 col-xs-12">Venue</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea id="venue" name="venue" class="form-control col-md-7 col-xs-12"></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="poster" class="control-label col-md-3 col-sm-3 col-xs-12">Poster</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input id="poster" name="poster" class="form-control col-md-7 col-xs-12" type="file">
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                </form>

                <?php if (isset($messages)) : ?>
                    <div class="alert alert-danger">
                        <ul>
                            <?php foreach ($messages as $field): ?>
                                <?php foreach ($field as $error): ?>
                                    <li><?= $error ?></li>
                                <?php endforeach; ?>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endif ?>
            </div>
        </div>
    </div>
</div>