<exercise-editor next-exercise-link='<?= $nextExerciseLink ?>'
                 :official-solution='<?= $this->json($official_solution ?? null) ?>'
                 :workshop='<?= $this->json($workshop) ?>'
                 :exercise='<?= $this->json($exercise) ?>'
                 :initial-files='<?= $this->json($initial_files ?? null) ?>'
                 :entry-point='<?= $this->json($entry_point) ?>'
                 :student='<?= $this->json($student) ?>'
                 :total-exercises='<?= $this->json($totalExerciseCount) ?>'
                 :links='<?= $this->json($links) ?>'
                 >

    <template #problem>
        <?= $problem ?>
    </template>

</exercise-editor>