<!doctype html>
<html lang="en-US">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><?= $pageTitle ?> - PHP School - Open Source Learning for PHP</title>
        <meta name="Description" content="<?= $pageDescription ?>">

        <link href="/img/favicon.ico" rel="shortcut icon" type="image/ico">
        <link href="/img/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72">
        <link href="/img/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144">

        <?php foreach ($this->getCss() as $css) : ?>
            <link href='<?= $css ?>' rel='stylesheet' type='text/css'>
        <?php endforeach; ?>
    </head>
    <body class="nav-md">
        <div class="container body">
            <div class="main_container">
                <div class="col-md-3 left_col">
                    <div class="left_col scroll-view">
                        <div class="navbar nav_title" style="border: 0;">
                            <a href="/admin" class="site_title"><span>PHP School</span></a>
                        </div>

                        <div class="clearfix"></div>

                        <!-- menu profile quick info -->
                        <div class="profile">
                            <div class="profile_pic">
                                <img src="https://www.gravatar.com/avatar/<?= md5($user->getEmail()) ?>" class="img-circle profile_img">
                            </div>
                            <div class="profile_info">
                                <span>Welcome,</span>
                                <h2><?= $user->getUsername() ?></h2>
                            </div>
                        </div>
                        <!-- /menu profile quick info -->
                        <div class="clearfix"></div>
                        <br>

                        <!-- sidebar menu -->
                        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                            <div class="menu_section active">
                                <h3>General</h3>
                                <ul class="nav side-menu" style="">
                                    <li class="active"><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu" style="display: block;">
                                            <li class="current-page"><a href="/admin/workshops/new">New Requests</a></li>
                                            <li><a href="/admin/workshops/all">All Workshops</a></li>
                                        </ul>
                                    </li>
                                    <li class="active"><a><i class="fa fa-cogs"></i> Settings <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu" style="display: block;">
                                            <li class="current-page"><a href="/admin/cache/clear">Clear Cache</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- top navigation -->
                <div class="top_nav">
                    <div class="nav_menu">
                        <nav class="" role="navigation">
                            <div class="nav toggle">
                                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                            </div>

                            <ul class="nav navbar-nav navbar-right">
                                <li class="">
                                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                        <img src="https://www.gravatar.com/avatar/<?= md5($user->getEmail()) ?>"><?= $user->getUsername() ?>
                                        <span class=" fa fa-angle-down"></span>
                                    </a>
                                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                                        <li><a href="javascript:;"> Profile</a></li>
                                        <li><a href="/logout"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <br>
                <br>
                <br>
                <!-- /top navigation -->

                <div class="right_col" role="main" style="min-height: 1162px;">
                    <?php foreach ($successMessages as $message): ?>
                        <div class="alert alert-success">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <?= $message ?>
                        </div>
                    <?php endforeach; ?>

                    <?php foreach ($errorMessages as $message): ?>
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <?= $message ?>
                        </div>
                    <?php endforeach; ?>

                    <div class="">
                        <div class="page-title">
                            <div class="title_left">
                                <h3><?= $pageTitle ?></h3>
                            </div>
                        </div>

                        <div class="clearfix"></div>
                        <?= $content ?>
                    </div>
                </div>
            </div>
        </div>

        <?php foreach ($this->getJs() as $js) : ?>
            <script src="<?= $js ?>"></script>
        <?php endforeach; ?>
    </body>
</html>

