<!doctype html>
<html id="page-top" lang="en-US">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><?= $pageTitle ?> - PHP School - Open Source Learning for PHP</title>
        <meta name="Description" content="<?= $pageDescription ?>">

        <link href="/img/favicon.ico" rel="shortcut icon" type="image/ico">
        <link href="/img/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72">
        <link href="/img/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144">

        <?= $this->renderCss() ?>

        <?php foreach ($this->getJs() as $js) : ?>
            <script <?= $js['tags'] ?> src="<?= $js['src'] ?>"></script>
        <?php endforeach; ?>

        <?php foreach ($this->getPreload() as $preload) : ?>
            <link rel="modulepreload" href="<?= $preload ?>">
        <?php endforeach; ?>
    </head>
    <body id="app" class="h-screen flex flex-col bg-gray-900">
        <Layout>
            <?= $content; ?>
        </Layout>
    </body>
</html>
