<!doctype html>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $pageTitle ?> - PHP School - Open Source Learning for PHP</title>
    <meta name="Description" content="<?= $pageDescription ?>">

    <link href="../img/favicon.ico" rel="shortcut icon" type="image/ico">
    <link href="../img/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72">
    <link href="../img/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144">

    <link rel="stylesheet" href="/css/core.min.css"/>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
</head>
<body>

<?= $content; ?>

<?= $this->fetch('includes/footer.phtml') ?>

<?php if ($route === '/install'): ?>
    <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="/js/main.js"></script>
<?php endif; ?>
</body>
</html>

