<p>There are numerous services exposed via the DI container. The services exposed to user-land code are listed below. These can be used in your exercises, custom-checks and other services you may create as part of your workshop. </p>

<p class="note note-warning">There are actually many more services exposed but these are for internal use of the workshop only. These services should not be used. If you decide to ignore the advice given here, you should take caution as backwards compatibility breaks may be introduced in minor versions. If you feel a service should be pubic, contact us and we can discuss it!</p>


<div class="method-list">
    <h5 class="method-list-title">Public Services</h5>
    <ul class="method-list-group">
        <li class="method-list-item">
            <h3 class="service-list-item-label">Colors\Color</h3>
            <p class="service-list-item-description">An instance of <a href="https://github.com/kevinlebrun/colors.php">Colors\Color</a>. Use this to apply ANSI styles to strings. For example, to colour a string ready to be printed to the console.</p>
        </li>
        <li class="method-list-item">
            <h3 class="service-list-item-label ">PhpSchool\PhpWorkshop\Output\OutputInterface</h3>
            <p class="service-list-item-description">A utility class to print content to the selected output. Currently this is the standard out connected to the terminal.</p>
        </li>
        <li class="method-list-item">
            <h3 class="service-list-item-label ">PhpSchool\PhpWorkshop\ExerciseRepository</h3>
            <p class="service-list-item-description">This is a repository of exercises allowing to retrieve exercises and get information regarding them.</p>
        </li>
        <li class="method-list-item">
            <h3 class="service-list-item-label ">PhpSchool\PhpWorkshop\Event\EventDispatcher</h3>
            <p class="service-list-item-description">EventDispatcher allows listening to events and inserting verifiers at certain points throughout the verifying/running process.</p>
        </li>
        <li class="method-list-item">
            <h3 class="service-list-item-label ">Symfony\Component\Filesystem\Filesystem</h3>
            <p class="service-list-item-description">An instance of <a href="http://symfony.com/doc/current/components/filesystem/introduction.html">Symfony\Component\Filesystem\Filesystem</a> allowing to perform simple IO operations.</p>
        </li>
        <li class="method-list-item">
            <h3 class="service-list-item-label ">PhpParser\Parser</h3>
            <p class="service-list-item-description">An instance of <a href="https://github.com/nikic/PHP-Parser">PhpParser\Parser</a> which allows to parse PHP code in to an AST structure.</p>
        </li>
        <li class="method-list-item">
            <h3 class="service-list-item-label ">PhpSchool\PhpWorkshop\CodePatcher</h3>
            <p class="service-list-item-description">Utility to apply patches to PHP code from Exercises.</p>
        </li>
        <li class="method-list-item">
            <h3 class="service-list-item-label ">PhpSchool\CliMenu\Terminal\TerminalInterface</h3>
            <p class="service-list-item-description">An implementation of <a href="https://github.com/php-school/cli-menu/blob/master/src/Terminal/TerminalInterface.php">PhpSchool\CliMenu\Terminal\TerminalInterface</a> which allows to retrieve and control the current terminal. For example getting the current terminal width.</p>
        </li>
        <li class="method-list-item">
            <h3 class="service-list-item-label ">PhpSchool\PhpWorkshop\MarkdownRenderer</h3>
            <p class="service-list-item-description">A utility to render Markdown to a string which should display nicely in a console terminal using ANSI escape sequences to format the output.</p>
        </li>
        <li class="method-list-item">
            <h3 class="service-list-item-label ">PhpSchool\PhpWorkshop\UserState</h3>
            <p class="service-list-item-description"></p>
        </li>
        <li class="method-list-item">
            <h3 class="service-list-item-label ">PhpSchool\PSX\SyntaxHighlighter</h3>
            <p class="service-list-item-description">An instance of <a href="https://github.com/php-school/psx#usage">PhpSchool\PSX\SyntaxHighlighter</a> which highlights PHP code using ANSI escape sequences ready to output on a console terminal.</p>
        </li>
        <li class="method-list-item">
            <h3 class="service-list-item-label ">PhpSchool\PhpWorkshop\Factory\ResultRendererFactory</h3>
            <p class="service-list-item-description"></p>
        </li>

    </ul>
</div>
