<p>There are various events triggered throughout the verifying and running of exercises. These events
can be used by <a href="/docs/reference/creating-listener-checks">Listener Checks</a> to hook in to the process
at various stages. This article details the events and the arguments available.</p>

<p>Each event implements <code>PhpSchool\PhpWorkshop\Event\EventInterface</code> where you can grab the parameters like
    <code>$event->getParameter('myParam'); </code> some events may have convenience methods for accessing certain
    parameters, please refer to the particular event class for more info.</p>

<p>There are 4 routes through the application, and the lists of events below each represent a timeline
of one of those routes.</p>

<h3 id="cli-verify">CLI Verify</h3>
<p>This is the route taken when using the <code>verify</code> command on a <code>CLI</code> type exercise.</p>
<h3 id="cli-run">CLI Run</h3>
<p>This is the route taken when using the <code>run</code> command on a <code>CLI</code> type exercise.</p>
<h3 id="cgi-verify">CGI Verify</h3>
<p>This is the route taken when using the <code>verify</code> command on a <code>CGI</code> type exercise.</p>
<h3 id="cgi-run">CGI Run</h3>
<p>This is the route taken when using the <code>run</code> command on a <code>CGI</code> type exercise.</p>

<?= $this->renderContentHeader('listening', 'Listening to Events') ?>

<p>Events can be listened to by attaching to the event dispatcher with any valid PHP callable:</p>

<pre><code lang="php">&lt;?php

$eventDispatcher = $container->get(PhpSchool\PhpWorkshop\Event\EventDispatcher:class);
$eventDispatcher->listen('verify.start', function (Event $event) {
    //do something
});

// you can also listen to multiple events in one call

$eventDispatcher->listen(['verify.start', 'run.start'], function (Event $event) {
    //do something
});
</code></pre>

<p>With the event dispatcher you can even do more interesting things, such as, at any event, you can insert
a verifier (any valid PHP callable) - it will be passed the event, the same as a normal listener, but it must return
an implementation of <code>PhpSchool\PhpWorkshop\Result\ResultInterface</code>. This will be evaluated and injected in
to the results for reporting on the CLI. <code>PhpSchool\PhpWorkshop\Result\SuccessInterface</code> instances will be
treated as successes and <code>PhpSchool\PhpWorkshop\Result\FailureInterface</code> instances will be treated as
failures. So you can actually fail a verification attempt via an event.</p>

<p class="note note-success">Learn more about results <a href="/docs/reference/result">here</a>.</p>

<p>This is useful for <em>Listener Checks</em>, for example, towards the end of the verifying process, you may
want to verify that some data was inserted to a database. If it was not you will return a failure, which will
be displayed on the CLI and will cause the verification attempt to fail.</p>

<p>How to insert verifiers:</p>

<pre><code lang="php">&lt;?php

$eventDispatcher = $container->get(PhpSchool\PhpWorkshop\Event\EventDispatcher:class);
$eventDispatcher->insertVerifier('verify.finish', function (Event $event) {
    if (!$this->checkDb()) {
        return Failure::fromNameAndReason('DB Check', 'DB Verification failed!');
    }
    return new Success('DB Check');
});

</code></pre>

<?= $this->renderContentHeader('events', 'Events') ?>

<div class="tabs-container">
    <ul class="tabs-menu">
        <li class="active"><a href="#tab-1">CLI Verify</a></li>
        <li class=""><a href="#tab-2">CLI Run</a></li>
        <li class=""><a href="#tab-3">CGI Verify</a></li>
        <li class=""><a href="#tab-4">CGI Run</a></li>
    </ul>
    <div class="tab">
        <div id="tab-1" class="tab-content">
        <div class="method-list">
            <h5 class="method-list-title">CLI Verify Events</h5>
            <ul class="method-list-group">
                <li class="method-list-item">
                    <h3 id="cli-verify-start" class="service-list-item-label">verify.start</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                    <p><small>This event is triggered right at the start of the verification process.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>

                    </p>
                </li>
                <li class="method-list-item">
                    <h3 id="cli-verify-pre-execute" class="service-list-item-label">verify.pre.execute</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                    <p><small>This event is triggered after the before checks have successfully finished running.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 id="cli-verify-ref-execute-pre" class="service-list-item-label">cli.verify.reference-execute.pre</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\CliExecuteEvent</code></p>
                    <p><small>This event is triggered just before the reference solution is run.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 id="cli-verify-ref-executing" class="service-list-item-label">cli.verify.reference.executing</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\CliExecuteEvent</code></p>
                    <p><small>This event is triggered while the reference solution is being executed. Here you can
                        actually interact with the program, for example if it kicked of a TCP server.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 id="cli-verify-ref-execute-fail" class="service-list-item-label">cli.verify.reference-execute.fail</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                    <p><small>This event is only triggered if the reference solution failed to finish correctly,
                        that is, with a non-zero exit code.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 id="cli-verify-student-execute-pre" class="service-list-item-label">cli.verify.student-execute.pre</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\CliExecuteEvent</code></p>
                    <p><small>This event is triggered just before the student's solution is run.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 id="cli-verify-student-executing" class="service-list-item-label">cli.verify.student.executing</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\CliExecuteEvent</code></p>
                    <p><small>This event is triggered while the student's solution is being executed. Here you can
                        actually interact with the program, for example if it kicked of a TCP server.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 id="cli-verify-student-execute-fail" class="service-list-item-label">cli.verify.student-execute.fail</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                    <p><small>This event is only triggered if the student's solution failed to finish correctly,
                        that is, with a non-zero exit code.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 id="cli-verify-post-execute" class="service-list-item-label">verify.post.execute</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                    <p><small>This event is triggered after the output verification and right before the after checks
                            are run.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 id="cli-verify-post-check" class="service-list-item-label">verify.post.check</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                    <p><small>This event is triggered after the before checks have finished running.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 id="cli-verify-finish" class="service-list-item-label">verify.finish</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                    <p><small>This event is triggered right at the end of the verification process.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
            </ul>
        </div>
    </div>
        <div id="tab-2" class="tab-content">
            <div class="method-list">
                <h5 class="method-list-title">CLI Run Events</h5>
                <ul class="method-list-group">
                    <li class="method-list-item">
                        <h3 id="cli-run-start" class="service-list-item-label">run.start</h3>
                        <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                        <p><small>This event is triggered right at the start of the running process.</small></p>
                        <p class="service-list-item-description">
                            Arguments
                        <dl class="check-description">
                            <dt>exercise</dt>
                            <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                            <dt>fileName</dt>
                            <dd><code>string</code></dd>
                        </dl>

                        </p>
                    </li>
                    <li class="method-list-item">
                        <h3 id="cli-run-student-execute-pre" class="service-list-item-label">cli.run.student-execute.pre</h3>
                        <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\CliExecuteEvent</code></p>
                        <p><small>This event is triggered just before the student's solution is run.</small></p>
                        <p class="service-list-item-description">
                            Arguments
                        <dl class="check-description">
                            <dt>exercise</dt>
                            <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                            <dt>fileName</dt>
                            <dd><code>string</code></dd>
                        </dl>
                        </p>
                    </li>
                    <li class="method-list-item">
                        <h3 id="cli-run-student-executing" class="service-list-item-label">cli.run.student.executing</h3>
                        <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\CliExecuteEvent</code></p>
                        <p><small>This event is triggered while the student's solution is being executed. Here you can
                            actually interact with the program, for example if it kicked of a TCP server.</small></p>
                        <p class="service-list-item-description">
                            Arguments
                        <dl class="check-description">
                            <dt>exercise</dt>
                            <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                            <dt>fileName</dt>
                            <dd><code>string</code></dd>
                        </dl>
                        </p>
                    </li>
                    <li class="method-list-item">
                        <h3 id="cli-run-finish" class="service-list-item-label">run.finish</h3>
                        <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                        <p><small>This event is triggered right at the end of the verification process.</small></p>
                        <p class="service-list-item-description">
                            Arguments
                        <dl class="check-description">
                            <dt>exercise</dt>
                            <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                            <dt>fileName</dt>
                            <dd><code>string</code></dd>
                        </dl>
                        </p>
                    </li>
                </ul>
            </div>
        </div>
        <div id="tab-3" class="tab-content">
            <div class="method-list">
                <h5 class="method-list-title">CGI Verify Events</h5>
                <ul class="method-list-group">
                    <li class="method-list-item">
                        <h3 id="cgi-verify-start" class="service-list-item-label">verify.start</h3>
                        <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                        <p><small>This event is triggered right at the start of the verification process.</small></p>
                        <p class="service-list-item-description">
                            Arguments
                        <dl class="check-description">
                            <dt>exercise</dt>
                            <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                            <dt>fileName</dt>
                            <dd><code>string</code></dd>
                        </dl>

                        </p>
                    </li>
                    <li class="method-list-item">
                        <h3 id="cgi-verify-ref-execute" class="service-list-item-label">verify.pre.execute</h3>
                        <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                        <p><small>This event is triggered after the before checks have successfully finished running.</small></p>
                        <p class="service-list-item-description">
                            Arguments
                        <dl class="check-description">
                            <dt>exercise</dt>
                            <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                            <dt>fileName</dt>
                            <dd><code>string</code></dd>
                        </dl>
                        </p>
                    </li>
                    <li class="method-list-item">
                        <h3 id="cgi-verify-ref-execute-pre" class="service-list-item-label">cgi.verify.reference-execute.pre</h3>
                        <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\CgiExecuteEvent</code></p>
                        <p><small>This event is triggered just before the reference solution is run.</small></p>
                        <p class="service-list-item-description">
                            Arguments
                        <dl class="check-description">
                            <dt>exercise</dt>
                            <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                            <dt>fileName</dt>
                            <dd><code>string</code></dd>
                        </dl>
                        </p>
                    </li>
                    <li class="method-list-item">
                        <h3 id="cgi-verify-ref-executing" class="service-list-item-label">cgi.verify.reference.executing</h3>
                        <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\CgiExecuteEvent</code></p>
                        <p><small>This event is triggered while the reference solution is being executed. Here you can
                                actually interact with the program, for example if it kicked of a TCP server.</small></p>
                        <p class="service-list-item-description">
                            Arguments
                        <dl class="check-description">
                            <dt>exercise</dt>
                            <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                            <dt>fileName</dt>
                            <dd><code>string</code></dd>
                        </dl>
                        </p>
                    </li>
                    <li class="method-list-item">
                        <h3 id="cgi-verify-ref-execute-fail" class="service-list-item-label">cgi.verify.reference-execute.fail</h3>
                        <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                        <p><small>This event is only triggered if the reference solution failed to finish correctly, that
                                is, with a non-zero exit code.</small></p>
                        <p class="service-list-item-description">
                            Arguments
                        <dl class="check-description">
                            <dt>exercise</dt>
                            <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                            <dt>fileName</dt>
                            <dd><code>string</code></dd>
                        </dl>
                        </p>
                    </li>
                    <li class="method-list-item">
                        <h3 id="cgi-verify-student-execute-pre" class="service-list-item-label">cgi.verify.student-execute.pre</h3>
                        <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\CgiExecuteEvent</code></p>
                        <p><small>This event is triggered just before the student's solution is run.</small></p>
                        <p class="service-list-item-description">
                            Arguments
                        <dl class="check-description">
                            <dt>exercise</dt>
                            <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                            <dt>fileName</dt>
                            <dd><code>string</code></dd>
                        </dl>
                        </p>
                    </li>
                    <li class="method-list-item">
                        <h3 id="cgi-verify-student-executing" class="service-list-item-label">cgi.verify.student.executing</h3>
                        <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\CgiExecuteEvent</code></p>
                        <p><small>This event is triggered while the student's solution is being executed. Here you can
                                actually interact with the program, for example if it kicked of a TCP server.</small></p>
                        <p class="service-list-item-description">
                            Arguments
                        <dl class="check-description">
                            <dt>exercise</dt>
                            <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                            <dt>fileName</dt>
                            <dd><code>string</code></dd>
                        </dl>
                        </p>
                    </li>
                    <li class="method-list-item">
                        <h3 id="cgi-verify-student-execute-fail" class="service-list-item-label">cgi.verify.student-execute.fail</h3>
                        <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                        <p><small>This event is only triggered if the student's solution failed to finish correctly,
                                that is, with a non-zero exit code.</small></p>
                        <p class="service-list-item-description">
                            Arguments
                        <dl class="check-description">
                            <dt>exercise</dt>
                            <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                            <dt>fileName</dt>
                            <dd><code>string</code></dd>
                        </dl>
                        </p>
                    </li>
                    <li class="method-list-item">
                        <h3 id="cgi-verify-post-execute" class="service-list-item-label">verify.post.execute</h3>
                        <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                        <p><small>This event is triggered after the output verification and right before the after
                                checks are run.</small></p>
                        <p class="service-list-item-description">
                            Arguments
                        <dl class="check-description">
                            <dt>exercise</dt>
                            <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                            <dt>fileName</dt>
                            <dd><code>string</code></dd>
                        </dl>
                        </p>
                    </li>
                    <li class="method-list-item">
                        <h3 id="cgi-verify-post-check" class="service-list-item-label">verify.post.check</h3>
                        <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                        <p><small>This event is triggered after the before checks have finished running.</small></p>
                        <p class="service-list-item-description">
                            Arguments
                        <dl class="check-description">
                            <dt>exercise</dt>
                            <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                            <dt>fileName</dt>
                            <dd><code>string</code></dd>
                        </dl>
                        </p>
                    </li>
                    <li class="method-list-item">
                        <h3 id="cgi-verify-finish" class="service-list-item-label">verify.finish</h3>
                        <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                        <p><small>This event is triggered right at the end of the verification process.</small></p>
                        <p class="service-list-item-description">
                            Arguments
                        <dl class="check-description">
                            <dt>exercise</dt>
                            <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                            <dt>fileName</dt>
                            <dd><code>string</code></dd>
                        </dl>
                        </p>
                    </li>
                </ul>
            </div>
        </div>
        <div id="tab-4" class="tab-content">
            <div class="method-list">
                <h5 class="method-list-title">CGI Run Events</h5>
                <ul class="method-list-group">
                    <li class="method-list-item">
                        <h3 id="cgi-run-start" class="service-list-item-label">run.start</h3>
                        <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                        <p><small>This event is triggered right at the start of the running process.</small></p>
                        <p class="service-list-item-description">
                            Arguments
                        <dl class="check-description">
                            <dt>exercise</dt>
                            <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                            <dt>fileName</dt>
                            <dd><code>string</code></dd>
                        </dl>

                        </p>
                    </li>
                    <li class="method-list-item">
                        <h3 id="cgi-run-student-execute-pre" class="service-list-item-label">cgi.run.student-execute.pre</h3>
                        <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\CgiExecuteEvent</code></p>
                        <p><small>This event is triggered just before the student's solution is run.</small></p>
                        <p class="service-list-item-description">
                            Arguments
                        <dl class="check-description">
                            <dt>exercise</dt>
                            <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                            <dt>fileName</dt>
                            <dd><code>string</code></dd>
                        </dl>
                        </p>
                    </li>
                    <li class="method-list-item">
                        <h3 id="cgi-run-student-executing" class="service-list-item-label">cgi.run.student.executing</h3>
                        <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\CgiExecuteEvent</code></p>
                        <p><small>This event is triggered while the student's solution is being executed. Here you can
                            actually interact with the program, for example if it kicked of a TCP server.</small></p>
                        <p class="service-list-item-description">
                            Arguments
                        <dl class="check-description">
                            <dt>exercise</dt>
                            <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                            <dt>fileName</dt>
                            <dd><code>string</code></dd>
                        </dl>
                        </p>
                    </li>
                    <li class="method-list-item">
                        <h3 id="cgi-run-finish" class="service-list-item-label">run.finish</h3>
                        <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                        <p><small>This event is triggered right at the end of the verification process.</small></p>
                        <p class="service-list-item-description">
                            Arguments
                        <dl class="check-description">
                            <dt>exercise</dt>
                            <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                            <dt>fileName</dt>
                            <dd><code>string</code></dd>
                        </dl>
                        </p>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>






