<p>There are various events triggered throughout the verifying and running of exercises. These events
can be used by <a href="/docs/reference/creating-listener-checks">Listener Checks</a> to hook in to the process
at various stages. This article details the events and the arguments available.</p>

<p>Each event implements <code>PhpSchool\PhpWorkshop\Event\EventInterface</code> where you can grab the parameters like
    <code>$event->getParameter('myParam'); </code> some events may have convenience methods for accessing certain
    parameters, please refer to the particular event class for more info.</p>

<p>There are 4 routes through the application, and the lists of events below each represent a timeline
of one of those routes.</p>

<h3>CLI Verify</h3>
<p>This is the route taken when using the <code>verify</code> command on a <code>CLI</code> type exercise.</p>
<h3>CLI Run</h3>
<p>This is the route taken when using the <code>run</code> command on a <code>CLI</code> type exercise.</p>
<h3>CGI Verify</h3>
<p>This is the route taken when using the <code>verify</code> command on a <code>CGI</code> type exercise.</p>
<h3>CGI Run</h3>
<p>This is the route taken when using the <code>run</code> command on a <code>CGI</code> type exercise.</p>

<?= $this->renderContentHeader('listening', 'Listening to Events') ?>

<p>Events can be listened to by attaching to the event dispatcher with any valid PHP callable:</p>

<pre><code lang="php">&lt;?php

$eventDispatcher = $container->get(PhpSchool\PhpWorkshop\Event\EventDispatcher:class);
$eventDispatcher->listen('verify.start', function (Event $event) {
    //do something
});

// you can also listen to multiple events in one call

$eventDispatcher->listen(['verify.start', 'run.start'], function (Event $event) {
    //do something
});
</code></pre>

<p>With the event dispatcher you can even do more interesting things, such as, at any event, you can insert
a verifier (any valid PHP callable) - it will be passed the event, the same as a normal listener, but it must return
an implementation of <code>PhpSchool\PhpWorkshop\Result\ResultInterface</code>. This will be evaluated and injected in
to the results for reporting on the CLI. <code>PhpSchool\PhpWorkshop\Result\SuccessInterface</code> instances will be
treated as successes and <code>PhpSchool\PhpWorkshop\Result\FailureInterface</code> instances will be treated as
failures. So you can actually fail a verification attempt via an event.</p>

<p>This is useful for <em>Listener Checks</em>, for example, towards the end of the verifying process, you may
want to verify that some data was inserted to a database. If it was not you will return a failure, which will
be displayed on the CLI and will cause the verification attempt to fail.</p>

<p>How to insert verifiers:</p>

<pre><code lang="php">&lt;?php

$eventDispatcher = $container->get(PhpSchool\PhpWorkshop\Event\EventDispatcher:class);
$eventDispatcher->insertVerifier('verify.finish', function (Event $event) {
    if (!$this->checkDb()) {
        return Failure::fromNameAndReason('DB Check', 'DB Verification failed!');
    }
    return new Success('DB Check');
});

</code></pre>

<?= $this->renderContentHeader('events', 'Events') ?>

<div class="tabs">
    <input type="radio" name="tabs" id="tab1" checked>
    <label for="tab1">
        <span>CLI Verify</span>
    </label>
    <input type="radio" name="tabs" id="tab2">
    <label for="tab2">
        <span>CLI Run</span>
    </label>
    <input type="radio" name="tabs" id="tab3">
    <label for="tab3">
        <span>CGI Verify</span>
    </label>
    <input type="radio" name="tabs" id="tab4">
    <label for="tab4">
        <span>CGI Run</span>
    </label>
    <div id="tab-content1" class="tab-content">
        <div class="method-list">
            <h5 class="method-list-title">CLI Verify Events</h5>
            <ul class="method-list-group">
                <li class="method-list-item">
                    <h3 class="service-list-item-label">verify.start</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                    <p><small>This event is triggered right at the start of the verification process.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>

                    </p>
                </li>
                <li class="method-list-item">
                    <h3 class="service-list-item-label">verify.pre.execute</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                    <p><small>This event is triggered after the before checks have successfully finished running.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 class="service-list-item-label">cli.verify.solution-execute.pre</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\CliExecuteEvent</code></p>
                    <p><small>This event is triggered just before the reference solution is run.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 class="service-list-item-label">cli.verify.solution.executing</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\CliExecuteEvent</code></p>
                    <p><small>This event is triggered while the reference solution is being executed. Here you can
                        actually interact with the program, for example if it kicked of a TCP server.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 class="service-list-item-label">cli.verify.solution-execute.fail</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                    <p><small>This event is only triggered if the reference solution failed to finish correctly,
                        that is, with a non-zero exit code.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 class="service-list-item-label">cli.verify.user-execute.pre</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\CliExecuteEvent</code></p>
                    <p><small>This event is triggered just before the student's solution is run.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 class="service-list-item-label">cli.verify.user.executing</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\CliExecuteEvent</code></p>
                    <p><small>This event is triggered while the student's solution is being executed. Here you can
                        actually interact with the program, for example if it kicked of a TCP server.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 class="service-list-item-label">cli.verify.user-execute.fail</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                    <p><small>This event is only triggered if the student's solution failed to finish correctly,
                        that is, with a non-zero exit code.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 class="service-list-item-label">verify.post.execute</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                    <p><small>This event is triggered after the output verification and right before the after checks
                            are run.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 class="service-list-item-label">verify.post.check</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                    <p><small>This event is triggered after the before checks have finished running.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 class="service-list-item-label">verify.finish</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                    <p><small>This event is triggered right at the end of the verification process.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
            </ul>
        </div>
    </div>
    <div id="tab-content2" class="tab-content">
        <div class="method-list">
            <h5 class="method-list-title">CLI Run Events</h5>
            <ul class="method-list-group">
                <li class="method-list-item">
                    <h3 class="service-list-item-label">run.start</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                    <p><small>This event is triggered right at the start of the running process.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>

                    </p>
                </li>
                <li class="method-list-item">
                    <h3 class="service-list-item-label">cli.run.user-execute.pre</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\CliExecuteEvent</code></p>
                    <p><small>This event is triggered just before the student's solution is run.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 class="service-list-item-label">cli.run.executing</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\CliExecuteEvent</code></p>
                    <p><small>This event is triggered while the student's solution is being executed. Here you can
                        actually interact with the program, for example if it kicked of a TCP server.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 class="service-list-item-label">run.finish</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                    <p><small>This event is triggered right at the end of the verification process.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
            </ul>
        </div>
    </div>
    <div id="tab-content3" class="tab-content">
        <div class="method-list">
            <h5 class="method-list-title">CGI Verify Events</h5>
            <ul class="method-list-group">
                <li class="method-list-item">
                    <h3 class="service-list-item-label">verify.start</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                    <p><small>This event is triggered right at the start of the verification process.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>

                    </p>
                </li>
                <li class="method-list-item">
                    <h3 class="service-list-item-label">verify.pre.execute</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                    <p><small>This event is triggered after the before checks have successfully finished running.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 class="service-list-item-label">cgi.verify.solution-execute.pre</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\CgiExecuteEvent</code></p>
                    <p><small>This event is triggered just before the reference solution is run.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 class="service-list-item-label">cgi.verify.solution.executing</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\CgiExecuteEvent</code></p>
                    <p><small>This event is triggered while the reference solution is being executed. Here you can
                            actually interact with the program, for example if it kicked of a TCP server.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 class="service-list-item-label">cgi.verify.solution-execute.fail</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                    <p><small>This event is only triggered if the reference solution failed to finish correctly, that
                            is, with a non-zero exit code.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 class="service-list-item-label">cgi.verify.user-execute.pre</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\CgiExecuteEvent</code></p>
                    <p><small>This event is triggered just before the student's solution is run.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 class="service-list-item-label">cgi.verify.user.executing</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\CgiExecuteEvent</code></p>
                    <p><small>This event is triggered while the student's solution is being executed. Here you can
                            actually interact with the program, for example if it kicked of a TCP server.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 class="service-list-item-label">cgi.verify.user-execute.fail</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                    <p><small>This event is only triggered if the student's solution failed to finish correctly,
                            that is, with a non-zero exit code.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 class="service-list-item-label">verify.post.execute</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                    <p><small>This event is triggered after the output verification and right before the after
                            checks are run.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 class="service-list-item-label">verify.post.check</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                    <p><small>This event is triggered after the before checks have finished running.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 class="service-list-item-label">verify.finish</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                    <p><small>This event is triggered right at the end of the verification process.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
            </ul>
        </div>
    </div>
    <div id="tab-content4" class="tab-content">
        <div class="method-list">
            <h5 class="method-list-title">CGI Run Events</h5>
            <ul class="method-list-group">
                <li class="method-list-item">
                    <h3 class="service-list-item-label">run.start</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                    <p><small>This event is triggered right at the start of the running process.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>

                    </p>
                </li>
                <li class="method-list-item">
                    <h3 class="service-list-item-label">cgi.run.user-execute.pre</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\CgiExecuteEvent</code></p>
                    <p><small>This event is triggered just before the student's solution is run.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 class="service-list-item-label">cgi.run.executing</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\CgiExecuteEvent</code></p>
                    <p><small>This event is triggered while the student's solution is being executed. Here you can
                        actually interact with the program, for example if it kicked of a TCP server.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
                <li class="method-list-item">
                    <h3 class="service-list-item-label">run.finish</h3>
                    <p>Event Class: <code>PhpSchool\PhpWorkshop\Event\Event</code></p>
                    <p><small>This event is triggered right at the end of the verification process.</small></p>
                    <p class="service-list-item-description">
                        Arguments
                    <dl class="check-description">
                        <dt>exercise</dt>
                        <dd><code>PhpSchool\PhpWorkshop\Exercise\ExerciseInterface</code></dd>
                        <dt>fileName</dt>
                        <dd><code>string</code></dd>
                    </dl>
                    </p>
                </li>
            </ul>
        </div>
    </div>
</div>






