<h2 id="reference-home" class="doc__title">Reference Documentation<a class="anchor" href="#reference-home">#</a><a href="#page-top" class="back-to-top">^ TOP</a></h2>

<p>In this section you will learn about the internals of the workshop application which will enable you to build robust and advanced workshops.</p>
<p>You can use this section as a useful reference to refer back to during the development of your workshop. </p>
<p>For a walk through approach detailing the initial setup of a workshop and the development of your first exercise, check out the <a href="docs/tutorial">Workshop Tutorial</a>.</p>

<h2 id="reference-sections" class="doc__title">Sections<a class="anchor" href="#reference-sections">#</a><a href="#page-top" class="back-to-top">^ TOP</a></h2>
<h3><a href="/docs/reference/container">The Container</a></h3>
<p>The workshop utilises a container to build and make services available. Learn how to register new services and register new ones.</p>

<h3><a href="/docs/reference/available-services">Available Services</a></h3>
<p>Learn about the services exposed by the container, many of them utilities you can use in your exercises, checks and other services.</p>

<h3><a href="/docs/reference/exercise-types">Exercise Types</a></h3>
<p>Exercises can be of either CLI or CGI type. Learn about the differences here and which one is right for your exercise.</p>

<h3><a href="/docs/reference/exercise-solutions">Exercise Solutions</a></h3>
<p>Exercise solutions can consist of one or many files, which could consist of an entire application. They can also contain Composer dependencies in order to model real-world scenarios.</p>
