<p>In this section you will learn about the internals of the workshop application which will enable you to build robust and advanced workshops.</p>
<p>You can use this section as a useful reference to refer back to during the development of your workshop. </p>
<p>For a walk through approach detailing the initial setup of a workshop and the development of your first exercise, check out the <a href="docs/tutorial">Workshop Tutorial</a>.</p>

<?= $this->renderDocHeader('reference-sections', 'Sections') ?>
<h3><a href="/docs/reference/container">The Container</a></h3>
<p>The workshop utilises a container to build and publish services. Learn how to register new services and replace existing ones.</p>

<h3><a href="/docs/reference/available-services">Available Services</a></h3>
<p>Learn about the services exposed by the container, many of them utilities you can use in your exercises, checks and other services.</p>

<h3><a href="/docs/reference/exercise-types">Exercise Types</a></h3>
<p>Exercises can be of either <code>CLI</code> or <code>CGI</code> type. Learn about the differences here and which one is right for your exercise.</p>

<h3><a href="/docs/reference/exercise-solutions">Exercise Solutions</a></h3>
<p>Exercise solutions can consist of one or many files, which could consist of an entire application. They can also contain Composer dependencies in order to model real-world scenarios.</p>

<h3><a href="/docs/reference/exercise-checks">Exercise Checks</a></h3>
<p>Learn what Exercise Checks are and how to use them in your exercise.</p>

<h3><a href="/docs/reference/bundled-checks">Bundled Checks</a></h3>
<p>Learn about the available Exercise Checks in the workshop framework and how to use them.</p>

<h3><a href="/docs/reference/creating-simple-checks">Creating Simple Checks</a></h3>
<p>Learn how to create your own Simple Check.</p>

<h3><a href="/docs/reference/events">Events</a></h3>
<p>Learn about all the events available for listening to in the workshop framework and how to listen to them.</p>

<h3><a href="/docs/reference/creating-listener-checks">Creating Listener Checks</a></h3>
<p>Learn how to utilise events to build a Listener Check by following a tutorial to build a Couch DB check.</p>

<h3><a href="/docs/reference/self-checking-exercises">Self Checking Exercise</a></h3>
<p>Add simple checking logic directly in your exercise.</p>

<h3><a href="/docs/reference/exercise-events">Exercise Events</a></h3>
<p>Listen to events directly in your exercise instead of building a custom check.</p>

<h3><a href="/docs/reference/patching-exercise-solutions">Patching Exercise Solutions</a></h3>
<p>Learn how to modify the student's solution on the fly, injecting variables, wrapping code in
in <code>try/catch</code> blocks, registering error handlers and so on.</p>
