<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><?= $pageTitle ?> - PHP School - Open Source Learning for PHP</title>
        <meta name="Description" content="<?= $pageDescription ?>">

        <link href="/img/favicon.ico" rel="shortcut icon" type="image/ico">
        <link href="/img/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72">
        <link href="/img/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144">

        <?= $this->renderCss() ?>
    </head>
    <body>
        <section>
            <div class="container login">
                <div class="content">
                    <pre class="blink">
  ____    __  __  ____        ____           __                    ___
 /\  _`\ /\ \/\ \/\  _`\     /\  _`\        /\ \                  /\_ \
 \ \ \L\ \ \ \_\ \ \ \L\ \   \ \,\L\_\   ___\ \ \___     ___    __\//\ \
  \ \ ,__/\ \  _  \ \ ,__/    \/_\__ \  /\'___\ \  _`\  / __`\ / __`\ \ \
   \ \ \/  \ \ \ \ \ \ \/       /\ \L\ \/\ \__/\ \ \ \ \/\ \L\ /\ \L\ \_\ \_
    \ \_\   \ \_\ \_\ \_\       \ `\____\ \____\\ \_\ \_\ \____\ \____/\____\
     \/_/    \/_/\/_/\/_/        \/_____/\/____/ \/_/\/_/\/___/ \/___/\/____/
                    </pre>
                    <form class="login-form" action="/login" method="POST">
                        <div class="field">
                            <input type="text" name="email" class="input-text" placeholder="Email" required="">
                        </div>
                        <div class="field">
                            <input type="password" name="password" class="input-text" placeholder="Password" required="">
                        </div>
                        <div class="form__actions">
                            <button class="button button--bold button-submit" type="submit">LOGIN</button>
                        </div>

                        <?php if (isset($messages)): ?>
                            <ul class="form__errors">
                                <?php foreach ($messages as $field): ?>
                                    <? foreach ($field as $error): ?>
                                        <li><?= $error ?></li>
                                    <?php endforeach; ?>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    </form>
                </div>
            </div>
        </section>
    </body>
</html>