<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><?= $pageTitle ?> - PHP School - Open Source Learning for PHP</title>
        <meta name="Description" content="<?= $pageDescription ?>">

        <link href="/img/favicon.ico" rel="shortcut icon" type="image/ico">
        <link href="/img/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72">
        <link href="/img/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144">

        <?php foreach ($this->getCss() as $css) : ?>
            <link href='<?= $css ?>' rel='stylesheet' type='text/css'>
        <?php endforeach; ?>
    </head>
    <body class="login">
        <div class="login_wrapper">
            <div class="animate form login_form">
                <section class="login_content">
                    <form lpformnum="1" action="/login" method="POST">
                        <h1>Login</h1>
                        <div>
                            <input type="text" name="email" class="form-control" placeholder="Email" required="">
                        </div>
                        <div>
                            <input type="password" name="password" class="form-control" placeholder="Password" required="">
                        </div>
                        <div>
                            <button class="btn btn-default submit" type="submit">Log in</button>
                        </div>

                        <div class="clearfix"></div>

                        <div class="separator">
                            <div class="clearfix"></div>
                            <br>
                        </div>


                    </form>
                </section>
                <?php if (isset($messages)): ?>
                    <div class="alert alert-danger">
                        <ul>
                            <?php foreach ($messages as $field): ?>
                                <? foreach ($field as $error): ?>
                                    <li><?= $error ?></li>
                                <?php endforeach; ?>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </body>
</html>