<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><?= $pageTitle ?> - PHP School - Open Source Learning for PHP</title>
        <meta name="Description" content="<?= $pageDescription ?>">

        <link href="/img/favicon.ico" rel="shortcut icon" type="image/ico">
        <link href="/img/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72">
        <link href="/img/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144">

        <?= $this->renderCss() ?>

        <?php foreach ($this->getJs() as $js) : ?>
            <script <?= $js['tags'] ?> src="<?= $js['src'] ?>"></script>
        <?php endforeach; ?>

        <?php foreach ($this->getPreload() as $preload) : ?>
            <link rel="modulepreload" href="<?= $preload ?>">
        <?php endforeach; ?>
    </head>
    <body class="bg-black h-screen w-full">
            <div class="content h-full mx-auto flex flex-col justify-center items-center ">
                <pre class="blink font-normal text-[13px] hidden md:block text-[#e91e63] mb-8">
 ____    __  __  ____        ____           __                     ___
/\  _`\ /\ \/\ \/\  _`\     /\  _`\        /\ \                   /\_ \
\ \ \L\ \ \ \_\ \ \ \L\ \   \ \ \L\_\   ___\ \ \___    ___    __  \//\ \
 \ \ ,__/\ \  _  \ \ ,__/    \/_\__ \ /\'___\ \  _`\  / __`\ / __`\ \ \ \
  \ \ \/  \ \ \ \ \ \ \/       /\ \L\ \/\ \__/\ \ \ \ \/\ \L\ /\ \L\ \_\ \_
   \ \_\   \ \_\ \_\ \_\       \ `\____\ \____\\ \_\ \_\ \____\ \____/\____\
    \/_/    \/_/\/_/\/_/        \/_____/\/____/ \/_/\/_/\/___/ \/___/\/____/
                </pre>
                <form class="w-[300px] flex flex-col justify-center items-center gap-y-4" action="/login" method="POST">
                    <input type="text" name="email" class="block w-full rounded-full border-0 px-4 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" placeholder="Email" required="">
                    <input type="password" name="password" class="block w-full rounded-full border-0 px-4 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" placeholder="Password" required="">
                    <button class="w-48 flex justify-center items-center text-white  text-base px-10 py-2 uppercase  rounded-full bg-pink-600 hover:bg-pink-500" type="submit">LOGIN</button>

                    <?php if (count($errors)): ?>
                        <ul class="text-xs text-center text-[#cc1717] my-3 p-3">
                            <?php foreach ($errors as $field): ?>
                                <?php foreach ($field as $error): ?>
                                    <li class="mb-3 last:mb-0"><?= $error ?></li>
                                <?php endforeach; ?>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                </form>
            </div>
    </body>
</html>