<header class="site-header site-header--slim">
    <?= $this->fetch('includes/site-nav.phtml') ?>
    <div class="container">
        <h1 class="site-header__title">API Documentation</h1>
        <p class="site-header__desc">API Documentation for building your own workshops!</p>
        <span class="curser"><svg class="svg-icon"><use xlink:href="/img/icons/icons.svg#svg-cursor"></use></svg></span>
    </div>
</header>
