<header class="site-header site-header--slim">
    <?= $this->fetch('includes/site-nav.phtml') ?>
    <div class="container">
        <h1 class="site-header__title">Documentation</h1>
        <p class="site-header__desc">Ready for the next step? <br> Use the PHP School workshop documentation to build you own workshop and help teach others PHP!</p>
        <div class="site-header__search" id="search">
            <input type="text" id="search-input" placeholder="Search docs...">
        </div>
    </div>
</header>
