<header class="site-header site-header--slim">
    <?= $this->fetch('includes/site-nav.phtml') ?>
    <div class="container">
        <h1 class="sub-header__title">
            Documentation
            <span class="curser"><svg class="svg-icon"><use xlink:href="/img/icons/icons.svg#svg-cursor"></use></svg></span>
        </h1>
        <p class="sub-header__desc">Ready for the next step? Here you can learn how to help others learn PHP with the PHP School workshop documentation</p>
        <div class="site-header__search" id="search">
            <input type="text" id="search-input" placeholder="Search docs...">
        </div>
    </div>
</header>
