<footer class="site-footer" role="contentinfo">
    <div class="container"></div>
    <div class="copyright">
        <p class="copyright__text">© Copyright <?= date('Y') ?></p>
        <p class="os__text">This site is <a href="<?= $this->getAttribute('links')['github-website'] ?>">open source on Github</a> & we welcome corrections/improvements.</p>
        <?= $this->fetch('includes/social-nav.phtml') ?>

        <div class="sponsor">
            <img id="sponsor__do" src="/img/do.png" title="Sponsored by Digital Ocean"/>
        </div>
    </div>
</footer>

<?= $this->fetch('includes/ga.phtml') ?>
