<footer class="site-footer" role="contentinfo">
    <div class="container"></div>
    <div class="copyright">
        <p class="copyright__text">© Copyright <?= date('Y') ?></p>
        <p class="os__text">This site is <a href="<?= $this->getAttribute('links')['github-website'] ?>">open source on Github</a> & we welcome corrections/improvements.</p>
        <?= $this->fetch('includes/social-nav.phtml') ?>

        <div class="sponsor">
            <a href="https://www.digitalocean.com" target="_blank">
                <img class="sponsor__logo" src="/img/do.png" title="Sponsored by Digital Ocean"/>
            </a>
            <a href="https://www.stickermule.com" target="_blank">
                <img class="sponsor__logo" src="/img/stickermule.png" title="Sponsored by StickerMule"/>
            </a>
        </div>
    </div>
</footer>

<?= $this->fetch('includes/ga.phtml') ?>
