<header class="site-header">
    <?= $this->fetch('includes/site-nav.phtml') ?>
    <div class="container">
        <figure class="logo"><?= $this->fetch('includes/icon.phtml', ['name' => "logo"]) ?></figure>
        <h1 class="header__title">
            <span class="header__typed"></span>
<!--            <span class="curser">--><?//= $this->fetch('includes/icon.phtml', ['name' => "cursor"]) ?><!--</span>-->
        </h1>
        <p class="header__desc">A revolutionary new way to learn PHP. Bring your imagination to life in an open learning eco-system.</p>
    </div>
</header>
