<header class="site-header site-header--slim">
    <?= $this->fetch('includes/site-nav.phtml') ?>
    <div class="container">
        <h1 class="site-header__title">Installation Troubleshooting</h1>
        <p class="site-header__desc">If you are having trouble installing PHP School workshops, then you may need to update some software.</p>
<!--        <span class="curser"><svg class="svg-icon"><use xlink:href="/img/icons/icons.svg#svg-cursor"></use></svg></span>-->
    </div>
</header>
