<header class="site-header site-header--slim">
    <?= $this->fetch('includes/site-nav.phtml') ?>
    <div class="container">
        <h1 class="sub-header__title">
            Installation <span class="install-header__typed"></span>
        </h1>
        <p class="sub-header__desc">If you are having trouble installing PHP School workshops, then you may need to update some software.</p>
    </div>
</header>
