<nav class="site-nav">
        <div class="menu-icon"><?= $this->fetch('includes/icon.phtml', ['name' => "menu"]) ?></div>
        <?= $this->fetch('includes/social-nav.phtml') ?>
        <ul class="site-nav__list">
            <?php if ($route === '/'): ?>
                <li class="site-nav__item">
                    <a href="#help" class="site-nav__link">Need Help?</a>
                </li>
                <li class="site-nav__item">
                    <a href="/install" class="site-nav__link">Installation Problems?</a>
                </li>
                <li class="site-nav__item">
                    <a href="/docs" class="site-nav__link">Build a workshop!</a>
                </li>
            <?php else: ?>
                <li class="site-nav__item">
                    <a href="/" class="site-nav__link">Home</a>
                </li>
                <li class="site-nav__item">
                    <a href="/install" class="site-nav__link">Installation Problems?</a>
                </li>
                <li class="site-nav__item">
                    <a href="/docs" class="site-nav__link">Documentation</a>
                </li>
            <?php endif; ?>
            <li class="site-nav__item">
                <a href="/submit" class="site-nav__link">Submit your workshop!</a>
            </li>
            <li class="site-nav__item">
                <a href="/events" class="site-nav__link">Events</a>
            </li>
        </ul>
</nav>
