<ul class="social-nav">
    <li class="social-nav__item"><a href="<?= $links['github'] ?>" class="social-nav__link" title="PHPSchool on Github"><?= $this->fetch('includes/icon.phtml', ['name' => "github"]) ?></a></li>
    <li class="social-nav__item"><a href="<?= $links['twitter'] ?>" class="social-nav__link" title="PHPSchool on Twitter"><?= $this->fetch('includes/icon.phtml', ['name' => "twitter"]) ?></a></li>
    <li class="social-nav__item"><a href="<?= $links['slack'] ?>" class="social-nav__link" title="PHPSchool on Slack"><?= $this->fetch('includes/icon.phtml', ['name' => "slack"]) ?></a></li>
</ul>
