<header class="site-header site-header--slim">
    <?= $this->fetch('includes/site-nav.phtml') ?>
    <div class="container">
        <figure class="logo"><?= $this->fetch('includes/icon.phtml', ['name' => "logo"]) ?></figure>
        <h1 class="site-header__title">Submit your workshop</h1>
        <p class="site-header__desc">PHP School is nothing without the community so it's great you are considering building and submitting a workshop.</p>
    </div>
</header>
