<?= $this->fetch('includes/api-docs-header.phtml') ?>

<section class="site-body">
    <div class="container">
        <p class="doc__side-trigger">Open Menu</p>
        <div class="docs">
            <div class="doc__side">
                <h3 class="doc__side-title">Namespaces</a></h3>
                <ul class="doc__side-list">
                    <?php foreach ($namespaces as $namespace): ?>
                        <li class="doc__side-item">
                            <a class="doc__side-link <?= $currentNamespace === $namespace['title'] ? 'current' : '' ?>"
                               href="/api-docs/<?= $namespace['slug'] ?>"><?= $namespace['title']; ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>

            <div class="doc__content">
                <?= $content; ?>
            </div>
        </div>
    </div>
</section>
