<div class="flex flex-col mx-auto max-w-3xl text-left text-gray-800 p-8">
    <?php if ($posts->isEmpty()) : ?>
        <div class="post">
            <h1>No posts yet!</h1>
        </div>
    <?php endif ?>

    <?php foreach ($posts as $post) : ?>
        <div class="p-8 border-b border-solid border-1 border-pink-600/40 text-lg last:border-none">
            <div class="text-center mb-3">
                <h1 class="text-4xl font-bold leading-normal mt-[9px] mb-3 mx-0 font-mono hover:text-[#e91e63]"><a href="/blog<?= $post->getMeta()->getLink() ?>"><?= $post->getMeta()->getTitle() ?></a></h1>
                <span class="text-xs font-bold hover:text-[#e91e63]"><a href="<?= $post->getMeta()->getAuthorLink() ?>"><?= $post->getMeta()->getAuthor() ?><a/></span>
                <span class="text-xs text-gray-400"> - <?= $post->getMeta()->getDate()->format('F j, Y') ?></span>
            </div>

            <?php if ($post->hasFeatureImage()) : ?>
                <div class="m-6 flex justify-center">
                    <a class="" href="/blog<?= $post->getMeta()->getLink() ?>">
                        <?= $post->getFeatureImage() ?>
                    </a>
                </div>
            <?php endif ?>

            <div class="text-[#888] mb-4 font-open-sans"> <?= $post->getExcerpt() ?></div>
            <p class="font-bold hover:text-[#e91e63] font-open-sans mb-2">
                <a href="/blog<?= $post->getMeta()->getLink() ?>">Read more&nbsp;&nbsp;&rsaquo;</a>
            </p>
        </div>
    <?php endforeach ?>

    <?php if ($pageNumber < $totalPages) : ?>
        <div class="p-7 left">
            <a class="uppercase font-bold font-mono text-xs hover:text-pink-500" href="/blog/page-<?= $pageNumber + 1 ?>">&laquo;&nbsp;OLDER</a>
        </div>
    <?php endif ?>
    <?php if ($pageNumber > 1) : ?>
        <div class="p-7  right">
            <a class="uppercase font-bold  font-mono text-xs hover:text-pink-500" href="/blog/page-<?= $pageNumber - 1 ?>">NEWER&nbsp;&raquo;</a>
        </div>
    <?php endif ?>
</div>
