<?= $this->fetch('includes/docs-header.phtml') ?>

<section class="site-body">
    <div class="container">
        <p class="doc__side-trigger">Open Menu</p>
        <div class="docs">
            <div class="doc__side">
                <?php foreach ($docs as $group): ?>
                    <h3 class="doc__side-title"><?= $group->getTitle(); ?></a></h3>
                    <ul class="doc__side-list">
                        <?php foreach ($group as $docSection): ?>
                            <li class="doc__side-item">

                                <?php if ($docSection->enabled()) : ?>
                                    <?php if ($docSection->getName() === 'index'): ?>
                                        <span class="doc__link__icon">
                                            <?= $this->fetch('includes/icon.phtml', ['name' => "home"]) ?>
                                        </span>
                                    <?php endif; ?>

                                    <a class="doc__side-link active"
                                        href="<?= $docSection->getHref() ?>">
                                        <?= $docSection->getTitle(); ?>
                                    </a>
                                <?php else: ?>
                                    <span class="doc__side-link"e
                                        href="<?= $docSection->getHref() ?>">
                                        <?= $docSection->getTitle(); ?>
                                    </span>
                                <?php endif; ?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endforeach; ?>
            </div>
            <div class="doc__content">
                <?= $content; ?>

                <div class="doc__controls">
                    <div class="doc__previous">
                        <?php if ($docs->hasPreviousSection($doc)) : ?>
                            <a class="" href="<?= $docs->getPreviousSection($doc)->getHref() ?>">⇠ <?= $docs->getPreviousSection($doc)->getTitle() ?></a>
                        <?php endif; ?>
                    </div>

                    <div class="doc__home">
                        <?php if ($docs->hasHome($doc)) : ?>
                            <a href="<?= $docs->getHome($doc)->getHref() ?>"><?= $this->fetch('includes/icon.phtml', ['name' => "home"]) ?></a>
                        <?php endif; ?>
                    </div>

                    <div class="doc__next">
                        <?php if ($docs->hasNextSection($doc)) : ?>
                            <a class="" href="<?= $docs->getNextSection($doc)->getHref() ?>"><?= $docs->getNextSection($doc)->getTitle() ?> ⇢</a>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
