<header class="site-header site-header--slim">
    <?= $this->fetch('includes/site-nav.phtml') ?>
    <div class="container">
        <h1 class="site-header__title">Upcoming Events</h1>
        <p class="site-header__desc">Upcoming PHP School meet-ups, see you there maybe?!</p>
    </div>
</header>
<section class="site-body">
    <div class="container">
        <p class="doc__side-trigger">Open Menu</p>
        <div class="docs">
            <div class="doc__side">
                <h3 class="doc__side-title">Previous Events</a></h3>
                <ul class="doc__side-list">
                    <?php foreach ($previousEvents as $previousEvent): ?>
                        <li class="doc__side-item">
                            <a class="doc__side-link">
                            <strong><?= $previousEvent->getDateTime()->format('l M jS Y - g:i A') ?></strong><br>
                            <?= $previousEvent->getName(); ?>
                                </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <div class="doc__content">
                <?php foreach ($events as $i => $event): ?>
                    <div class="event">
                        <h3 class="item event__date"><?= $event->getDateTime()->format('l M jS - g:i A') ?></h3>
                        <h2 class="item event__name"><?= $event->getName() ?></h2>

                        <?php if ($event->getPoster()) : ?>
                            <a target="_blank" class="item event__poster" href="/uploads/<?= $event->getPoster() ?>">
                                <img src="/uploads/<?= $event->getPoster() ?>">
                            </a>
                        <?php endif ?>

                        <p class="item event__description"><?= $event->getDescription() ?></p>
                        <p class="item event_venue">
                            <a target="_blank" href="http://maps.google.com/?q=<?= implode(',', $event->getVenueLines()) ?>">
                                <address>
                                    <?php foreach ($event->getVenueLines() as $line): ?>
                                        <?= $line ?><br>
                                    <?php endforeach ?>
                                </address>
                            </a>
                        </p>
                    </div>

                    <?php if ($i + 1 < count($events)): ?>
                        <hr>
                    <?php endif; ?>
                <?php endforeach ?>
            </div>
        </div>
    </div>
</section>
