
<?= $this->fetch('includes/home-header.phtml') ?>
<section class="site-body">
    <div class="container">
        <div class="introduction" id="getting-started">
            <div class="introduction__info">
                <h2>What is PHP School?</h2>

                <p>Welcome to PHP School! A dedicated community based learning platform that will teach you the core skills in PHP. The concept behind PHP School is simple, workshops are run from the command line, somewhere every developer should be familiar with. Each workshop covers a different topic, some beginner, some advanced. You're not restricted to a schedule, you go at your own pace with no pressure.</p>
                <h3>Getting Started</h3>
                <p>Before you can start our courses there are a few requirements which should be met:</p>
                <ul>
                    <li>You will need PHP with a version of at least 5.6 and a recent version of <a href="https://getcomposer.org/" target="_blank">Composer</a> installed</li>
                    <li>If you are running Windows, you will need a few more things which can be found on our <a href="/install">install</a> page.</li>
                    <li>You will also need a Text Editor so you can work through the workshops. You can try <a href="https://atom.io/" target="_blank">Atom</a> or <a href="https://www.sublimetext.com/" target="_blank">Sublime</a> if you don't already have one.</li>
                </ul>

                <p>Now all you have to do is pick a <a href="#core-workshop">workshop</a> and go through the exercises! Each exercise increases in difficulty, guiding you through the core concepts of PHP.</p>
            </div>
            <div class="introduction__video">
                <div class="terminal">
                    <div class="terminal-head">
                        <span class="terminal__button"></span>
                        <span class="terminal__button"></span>
                        <span class="terminal__button"></span>
                    </div>
                    <div class="terminal__body terminal--image">
                        <img src="/img/php-school.gif"/>
                    </div>
                </div>
            </div>
        </div>

        <div id="core-workshop" class="core-workshop">
            <div class="core-workshop__info">
                <h2><a href="#core-workshop">Core Workshops</a></h2>
                <p>Workshops created by the PHP School team!</p>
                <p>We've built an intricate framework specifically designed to make the creation of simple to advanced workshops pain free. It has a simple yet powerful verification system with code injection and language parsing to give workshop creators amazing flexibility in what they build.</p>
                <p></p>
            </div>
            <div class="core-workshop__courses">

                <div class="workshop__course">
                    <h3><a href="https://github.com/php-school/learn-you-php">Learn You PHP!</a></h3>
                    <p class="workshop-description">An introduction to PHP's core features: i/o, http, arrays, exceptions and so on.</p>

                    <div class="terminal">
                        <div class="terminal__body">
                            <p>composer global require php-school/learn-you-php:~0.1</p>
                            <p>learnyouphp</p>
                        </div>
                    </div>
                </div>
                <div class="workshop__course">
                    <h3><a href="#">PHP Basics</a></h3>
                    <p class="workshop-description">Mastering the basic concepts of PHP</p>

                    <div class="terminal">
                        <div class="terminal__body">
                            <p>Coming soon</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div id="community-workshop" class="community-workshop">
            <div class="community-workshop__info">
                <h2><a href="#community-workshop">Community workshops</a></h2>
                <p>At the core, PHP School is a workshop framework which allows you to run a set of exercises. It has been designed in a way that you can easily build your own workshops, focusing on any subject you please.</p>
                <p>Visit the <a href="/docs">documentation</a> to learn how to build your own Workshop.</p>
                <p>Check out <a href="/docs">this page</a> to submit your workshop so it appears here and can be installable with the workshop manager!</p>
            </div>
            <div class="community-workshop__courses">
                <div class="workshop__course">
                    <h3><a href="https://github.com/NastasiaSaby/callable-functions">Callable Functions</a></h3>
                    <p class="workshop-description">A PHP School workshop about callable functions with arrays.</p>

                    <div class="terminal">
                        <div class="terminal__body">
                            <p>composer global require nastasia/callable-functions:^0.3</p>
                            <p>callablefunctions</p>
                        </div>
                    </div>
                    <p class="termianl__meta">Made by: <a href=" https://twitter.com/saby_nastasia">Nastasia Saby</a></p>
                </div>

                <div class="terminal">
                    <div class="terminal__body">
                        <p>Contact us to get your workshop listed here!</p>
                    </div>
                </div>
                <p class="termianl__meta">Made by: The PHP community</p>
            </div>
        </div>
        <div class="help" id="help">
            <div class="help__icons"><?= $this->fetch('includes/social-nav.phtml') ?></div>
            <div class="help__info">
                <h2>Need help?</h2>
                <p>If you need help or want to contribute to PHP School, you can chat on <a href="<?= $links['slack'] ?>" target="_blank">Slack</a>, create issues and send PR's on <a href="<?= $links['github'] ?>" target="_blank">GitHub</a>. We also have a <a href="<?= $links['twitter'] ?>" target="_blank">Twitter</a> account where we will push out news and information!</p>
                <br>
                <p>If you have any issues with any of the workshops or just general getting started questions, you can create an issue <a href="<?= $links['discussions'] ?>" target="_blank">here</a> and someone will get back to you whenever it is possible. Feel free to also jump on and help other people with their issues. This type of project works best when everyone gets involved.</p>
            </div>
        </div>
    </div>
</section>
<section class="team">
    <div class="container">
        <h2>Our team</h2>
        <p class="team__desc">We are a couple of friends working in our spare time to improve the quality of PHP learning resources. We want to empower you to build, whether it be a hobbyist project or a tool to help educate the world. Neither skill nor age should be a barrier to learning, the PHP School team are committed to helping train the next generation of coders who will go on to change the world!</p>
        <ul class="team__list">
            <li class="team__item">
                <a href="https://github.com/AydinHassan" target="_blank">
                    <figure class="team__image">
                        <img src="https://avatars0.githubusercontent.com/u/2817002?v=3&s=460" alt="@AydinHassan">
                    </figure>
                    <p class="team__name">Aydin Hassan</p>
                    <p class="team__role">Developer</p>
                    <?= $this->fetch('includes/icon.phtml', ['name' => "github"]) ?>
                </a>
            </li>
            <li class="team__item">
                <a href="https://github.com/mikeymike" target="_blank">
                    <figure class="team__image">
                        <img src="https://avatars0.githubusercontent.com/u/2174476?v=3&s=460" alt="@mikeymike">
                    </figure>
                    <p class="team__name">Michael Woodward</p>
                    <p class="team__role">Developer</p>
                    <?= $this->fetch('includes/icon.phtml', ['name' => "github"]) ?>
                </a>
            </li>
            <li class="team__item">
                <a href="https://github.com/shakyShane" target="_blank">
                    <figure class="team__image">
                        <img src="https://avatars3.githubusercontent.com/u/1643522?v=3&s=460" alt="@shakeyShane">
                    </figure>
                    <p class="team__name">Shane Osbourne</p>
                    <p class="team__role">Developer</p>
                    <?= $this->fetch('includes/icon.phtml', ['name' => "github"]) ?>
                </a>
            </li>
            <li class="team__item">
                <a href="https://github.com/chris3ailey" target="_blank">
                    <figure class="team__image">
                        <img src="../img/ChrisBailey.jpg" alt="@chris3ailey">
                    </figure>
                    <p class="team__name">Chris Bailey</p>
                    <p class="team__role">Designer</p>
                    <?= $this->fetch('includes/icon.phtml', ['name' => "github"]) ?>
                </a>
            </li>
            <li class="team__item">
                <a href="https://github.com/OliverChenery" target="_blank">
                    <figure class="team__image">
                        <img src="https://avatars1.githubusercontent.com/u/10711847?v=3&s=460" alt="@OliverChenery">
                    </figure>
                    <p class="team__name">Oliver Chenery</p>
                    <p class="team__role">Designer</p>
                    <?= $this->fetch('includes/icon.phtml', ['name' => "github"]) ?>
                </a>
            </li>
        </ul>
    </div>
</section>

<section class="inspiration">
    <div class="container">
        <div class="inspiration__content">
            <figure class="inspiration__image">
                <img src="/img/svg/node-school-logo.svg" />
            </figure>
            <article class="inspiration__info">
                <h2 class="inspiration__title">Our inspiration</h2>
                <p>As developers who regularly use and advocate open source software, we have always loved the spirit of giving back. We work in a truly unique industry which is held together by people providing for free.</p>
                <p>Thank you <a href="http://nodeschool.io/" target="_blank">NodeSchool</a> for inspiring us to create PHP School, if Node & JavaScript is your thing, we recommend you check them out. When we saw what the NodeSchool community had achieved together, we knew we had to bring it over to the PHP world.</p>

                <a href="http://nodeschool.io/" target="_blank" class="inspiration__link button">NodeSchool</a>
            </article>
        </div>
    </div>
</section>
