<?= $this->fetch('includes/home-header.phtml') ?>
<div class="site-body">
    <div class="container">
        <div class="introduction" id="getting-started">
            <div class="introduction__info">
                <h2 class="introduction__title">What is PHP School?</h2>
                <p>Welcome to PHP School! A dedicated community based learning platform that will teach you the core skills in PHP. The concept behind PHP School is small standalone workshops, workshops are run from the command line, somewhere every developer should be familiar with.</p>
                <p>Each workshop covers a different topic, some beginner, some advanced. You're not restricted to a schedule, you go at your own pace with no pressure.</p>
            </div>
            <figure class="introduction__image">
                <figcaption class="introduction__caption">
                    <span class="introduction__step">1</span>
                    Select an exercise
                </figcaption>
                <img src="../img/intro-01.jpg">
            </figure>
            <figure class="introduction__image">
                <figcaption class="introduction__caption">
                    <span class="introduction__step">2</span>
                    Complete the challenge
                </figcaption>
                <img src="../img/intro-02.jpg">
            </figure>
            <figure class="introduction__image">
                <figcaption class="introduction__caption">
                    <span class="introduction__step">3</span>
                    Get instant feedback
                </figcaption>
                <img src="../img/intro-03.jpg">
            </figure>
        </div>

        <div class="installation" id="installation">
            <div class="installation__info">
                <h2 class="installation__title">Getting Started</h2>
                <?php if ($userAgent->is('Windows')) : ?>
                    <p>Windows users need to do a <a href="/install#windows">few more annoying things first</a>.</p>
                <?php endif; ?>
                <p>In order to get started with PHP School workshops, you first need to install the workshop manager. Before we can do this we need to check you have a few things:</p>
                <ul>
                    <li>You will need PHP with a version of at least 5.6 although we recommend using the <a href="https://secure.php.net/releases/">latest available.</a></li>
                    <li>You will also need a Text Editor so you can work through the workshops. You can try <a href="https://atom.io/" target="_blank">Atom</a> or <a href="https://www.sublimetext.com/" target="_blank">Sublime</a> if you don't already have one.</li>
                </ul>
                <p>Once the above are satisfied, run the following commands in your terminal, to install the workshop manager. The final command will verify your installation and will give you tips on how to resolve any issues.</p>
                <div class="terminal">
                    <div class="terminal-head">
                        <span class="terminal__button"></span>
                        <span class="terminal__button"></span>
                        <span class="terminal__button"></span>
                    </div>
                    <div class="terminal__body">
                        <p>curl -O https://php-school.github.io/workshop-manager/workshop-manager.phar</p>
                        <p>mv workshop-manager.phar /usr/local/bin/workshop-manager</p>
                        <p>chmod +x /usr/local/bin/workshop-manager</p>
                        <p>workshop-manager verify</p>
                    </div>
                </div>
            </div>
            <div class="installation__workshop">
                <h2>Workshop Manager usage</h2>
                <p>The workshop manager is a tool to search, install and remove PHP School workshops. See below for usage instructions. Please visit the <a href="https://github.com/php-school/workshop-manager" target="_blank">Workshop Manager GitHub Repository</a> for more detailed instructions.</p>
                <p><code>workshop-manager list</code></p>
                <p>Lists the available commands. </p>
                <p><code>workshop-manager search &lt;topic&gt;</code></p>
                <p>Search for a workshop covering a particular topic, providing no arguments will list all the available workshops.</p>
                <p><code>workshop-manager install &lt;workshopname&gt;</code></p>
                <p>Install a workshop.</p>
                <p><code>workshop-manager uninstall &lt;workshopname&gt;</code></p>
                <p>Remove a workshop.</p>
                <br>
                <p>Now we know how to use the Workshop Manager - go forth an install a workshop!</p>
                <a class="button" href="#core-workshop">To the workshops!</a>
            </div>
        </div>

        <div id="core-workshop" class="workshop">
            <figure class="workshop__image">
                <img src="../img/core-workshops.png">
            </figure>
            <div class="workshop__info">
                <h2 class="workshop__title"><a href="#core-workshop">Core Workshops</a></h2>
                <p>Workshops created by the PHP School team!</p>
                <p>We've built an intricate framework specifically designed to make the creation of simple to advanced workshops pain free. It has a simple yet powerful verification system with code injection and language parsing to give workshop creators amazing flexibility in what they build.</p>
            </div>
            <div class="workshop__courses">
                <?php /** @var \PhpSchool\Website\Entity\Workshop $workshop */?>
                <?php foreach ($coreWorkshops as $workshop): ?>
                    <div class="workshop__course">
                        <h3><a href="<?= $workshop->getRepoUrl() ?>"><?= $workshop->getDisplayName() ?></a></h3>
                        <p class="workshop__description"><?= $workshop->getDescription() ?></p>

                        <div class="terminal">
                            <div class="terminal__body">
                                <p>workshop-manager install <?= $workshop->getCode() ?></p>
                                <p><?= $workshop->getCode() ?></p>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>


        <div id="community-workshop" class="workshop">

            <figure class="workshop__image">
                <img src="../img/community-workshops.png">
            </figure>

            <div class="workshop__info">
                <h2 class="workshop__title"><a href="#community-workshop">Community workshops</a></h2>
                <p>At the core, PHP School is a workshop framework which allows you to run a set of exercises. It has been designed in a way that you can easily build your own workshops, focusing on any subject you please.</p>
                <p>Visit the <a href="/docs">documentation</a> to learn how to build your own Workshop.</p>
                <p>Check out <a href="/docs">this page</a> to submit your workshop so it appears here and can be installable with the workshop manager!</p>
            </div>
            <div class="workshop__courses">
                <?php /** @var \PhpSchool\Website\Entity\Workshop $workshop */?>
                <?php foreach ($communityWorkshops as $workshop): ?>
                    <div class="workshop__course">
                        <h3><a href="<?= $workshop->getRepoUrl() ?>"><?= $workshop->getDisplayName() ?></a></h3>
                        <p class="workshop-description"><?= $workshop->getDescription() ?></p>
                        <div class="terminal">
                            <div class="terminal__body">
                                <p>workshop-manager install <?= $workshop->getCode() ?></p>
                                <p><?= $workshop->getCode() ?></p>
                            </div>
                        </div>
                        <?php if ($workshop->getSubmitterContact()) : ?>
                            <p class="termianl__meta">Made by: <a href="<?= $workshop->getSubmitterContact() ?>"><?= $workshop->getSubmitterName() ?></a></p>
                        <?php else : ?>
                            <p class="termianl__meta">Made by: <?= $workshop->getSubmitterName() ?></p>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>

        <div class="help" id="help">
            <div class="help__icons"><?= $this->fetch('includes/social-nav.phtml') ?></div>
            <div class="help__info">
                <h2>Need help?</h2>
                <p>If you need help or want to contribute to PHP School, you can chat on <a href="<?= $links['slack'] ?>" target="_blank">Slack</a>, create issues and send PR's on <a href="<?= $links['github'] ?>" target="_blank">GitHub</a>. We also have a <a href="<?= $links['twitter'] ?>" target="_blank">Twitter</a> account where we will push out news and information!</p>
                <p>If you have any issues with any of the workshops or just general getting started questions, you can create an issue <a href="<?= $links['discussions'] ?>" target="_blank">here</a> and someone will get back to you whenever it is possible. Feel free to also jump on and help other people with their issues. This type of project works best when everyone gets involved.</p>
            </div>
        </div>

    </div>
    </div>

    <section class="inspiration">
        <div class="container">
            <div class="inspiration__content">
                <figure class="inspiration__image">
                    <img src="/img/svg/node-school-logo.svg" />
                </figure>
                <article class="inspiration__info">
                    <h2 class="inspiration__title">Our inspiration</h2>
                    <p>As developers who regularly use and advocate open source software, we have always loved the spirit of giving back. We work in a truly unique industry which is held together by people providing for free.</p>
                    <p>Thank you <a href="http://nodeschool.io/" target="_blank">NodeSchool</a> for inspiring us to create PHP School, if Node & JavaScript is your thing, we recommend you check them out. When we saw what the NodeSchool community had achieved together, we knew we had to bring it over to the PHP world.</p>

                    <a href="http://nodeschool.io/" target="_blank" class="inspiration__link button">NodeSchool</a>
                </article>
            </div>
        </div>
    </section>
