<?php /** @var \Slim\Views\PhpRenderer $this */?>

<?= $this->fetch('includes/install-header.phtml') ?>

<section class="site-body">
    <div class="container">

        <h1>Installation Help</h1>

        <div class="installer-questions">
            <?php //Rendered with JS @see install.js ?>
        </div>

        <?php foreach ($guides as $guide) : ?>
            <?= $this->fetch(sprintf('includes/guides/%s.phtml', $guide)) ?>
        <?php endforeach; ?>

    </div>
</section>

<script></script>
