<h2 class="doc__title" id="<?= $namespace['namespace']; ?>"><?= $namespace['namespace']; ?></h2>

<?php if (!empty($namespace['interfaces'])) : ?>
    <h3>Interfaces</h3>
    <ul class="docs__std__list__note">
        <?php foreach ($namespace['interfaces'] as $interface): ?>
            <li><a href="/api-docs/<?= $this->slugClass($namespace['namespace']); ?>/<?= $this->slugClass($interface['name']) ?>"><?= $interface['name'] ?></a></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>

<?php if (!empty($namespace['abstracts'])) : ?>
    <h3>Abstracts</h3>
    <ul class="docs__std__list__note">
        <?php foreach ($namespace['abstracts'] as $class): ?>
            <li><a href="/api-docs/<?= $this->slugClass($namespace['namespace']); ?>/<?= $this->slugClass($class['name']) ?>"><?= $class['name'] ?></a></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>

<?php if (!empty($namespace['classes'])) : ?>
    <h3>Classes</h3>
    <ul class="docs__std__list__note">
        <?php foreach ($namespace['classes'] as $class): ?>
            <li><a href="/api-docs/<?= $this->slugClass($namespace['namespace']); ?>/<?= $this->slugClass($class['name']) ?>"><?= $class['name'] ?></a></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>

<?php //foreach ($namespace['classes'] as $class): ?>
<!---->
<!--    --><?//= $this->renderContentHeader($class['name'], $class['name']) ?>
<!--    --><?php //foreach ($class['methods'] as $method): ?>
<!--        <h4>--><?//= $this->fetch('includes/doc/method.phtml', ['method' => $method]) ?><!--</h4>-->
<!--        --><?php //if ($method['shortDescription']): ?>
<!--            <p>--><?//= $method['shortDescription'] ?><!--</p>-->
<!--        --><?php //endif; ?>
<!---->
<!--        <div class="method-list">-->
<!--            <h5 class="method-list-title">Parameters</h5>-->
<!--            <table class="doc__api-param-table">-->
<!--                <tbody>-->
<!--                    --><?php //foreach ($method['params'] as $param): ?>
<!--                        <tr>-->
<!--                            <td class="col-one"><code>$--><?//= $param['name'] ?><!--</code></td>-->
<!--                            <td>-->
<!--                                <span class="type">--><?//= $param['typeHint'] ?><!--</span>-->
<!--                                --><?//= $param['description'] ?? 'No Description available' ?>
<!--                            </td>-->
<!--                        </tr>-->
<!--                    --><?php //endforeach; ?>
<!--                </tbody>-->
<!--            </table>-->
<!--        </div>-->
<!--        <div class="method-list">-->
<!--            <h5 class="method-list-title">Return Value</h5>-->
<!--            <table class="doc__api-param-table">-->
<!--                <tbody>-->
<!--                    <tr>-->
<!--                        <td class="col-one"><code>--><?//= $method['returnType'] ?><!--</code></td>-->
<!--                        <td>--><?//= $method['returnTypeDescription'] ?><!--</td>-->
<!--                    </tr>-->
<!--                </tbody>-->
<!--            </table>-->
<!--        </div>-->
<!--    --><?php //endforeach; ?>
<?php //endforeach; ?>