<!DOCTYPE html>
<html>

<head>
    <?= $this->renderCss() ?>

    <?php foreach ($this->getJs() as $js) : ?>
        <script <?= $js['tags'] ?> src="<?= $js['src'] ?>"></script>
    <?php endforeach; ?>

    <?php foreach ($this->getPreload() as $preload) : ?>
        <link rel="modulepreload" href="<?= $preload ?>">
    <?php endforeach; ?>

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Work+Sans:wght@400;700&display=swap" rel="stylesheet">
</head>

<body id="app">
    <Home></Home>
</body>

</html>