<?= $this->fetch('includes/submit-header.phtml') ?>

<section class="site-body">
    <div class="container">
        <div class="ws-submit">
            <div class="ws-submit__content">
                <h2>Built a workshop?</h2>
                <p>Through this form you can submit your workshop for approval, once approved your workshop will appear on the website and be installable by the workshop manager. To learn how to build a workshop, head over to the <a href="/docs">docs</a> or jump on to <a href="<?= $links['slack'] ?>">slack</a> for any help!</p>

                <h2>What is the approval process?</h2>
                <p>We are just making sure the quality is high and there is not lots of duplicated content across the workshops. We want PHP School to lead the way in quality education material.</p>
            </div>
            <div class="ws-submit__form">
                <form id="ws-submit-form" action="/submit" method="get" class="form" _lpchecked="1">
                    <div class="field">
                        <label for="email">Your Email Address <span class="required">*</span></label>
                        <p class="info">This is used just to send you a notification when your workshop is approved.</p>
                        <div class="input-box">
                            <input name="email" id="email" class="input-text ws-submit__input email" type="text" placeholder="myname@example.com" required="">
                            <ul class="form__errors email-errors"></ul>
                        </div>
                    </div>
                    <div class="field">
                        <label for="name">Your Name <span class="required">*</span> </label>
                        <p class="info">The name of workshop creator, shown on the homepage for bragging rights!</p>
                        <div class="input-box">
                            <input name="name" id="name" class="input-text ws-submit__input name" type="text" placeholder="Jane Doe" required="">
                            <ul class="form__errors name-errors"></ul>
                        </div>
                    </div>
                    <div class="field">
                        <label for="contact">Your Contact</label>
                        <p class="info">For example your Twitter or GitHub, it is shown with your name next to the workshop on the homepage.</p>
                        <div class="input-box">
                            <input name="contact" id="contact" class="input-text ws-submit__input contact" type="text" placeholder="https://twitter.com/your-name">
                            <ul class="form__errors contact-errors"></ul>
                        </div>
                    </div>
                    <div class="field">
                        <label for="workshop-name">Workshop Name <span class="required">*</span></label>
                        <div class="input-box">
                            <input name="workshop-name" id="workshop-name" class="input-text ws-submit__input workshop-name" type="text" placeholder="Learn You PHP!" required="">
                            <ul class="form__errors workshop-name-errors"></ul>
                        </div>
                    </div>
                    <div class="field">
                        <label for="github-url">GitHub Repository URL <span class="required">*</span></label>
                        <div class="input-box">
                            <input name="github-url" id="github-url" class="input-text ws-submit__input gh" type="text" name="github-url" placeholder="https://github.com/php-school/learn-you-php" required="">
                            <ul class="form__errors gh-errors"></ul>
                        </div>
                    </div>
                    <div class="form__actions">
                        <button type="submit" class="button button--bold button-submit"><span>Submit</span>
                            <div class="loader-wapper">
                                <div class="loader"></div>
                            </div>
                            <div class="button-submit__success">
                                <svg class="svg-icon" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:a="http://ns.adobe.com/AdobeSVGViewerExtensions/3.0/" x="0px" y="0px" width="167.2px" height="121.5px" viewBox="0 0 167.2 121.5" enable-background="new 0 0 167.2 121.5" xml:space="preserve"><defs></defs><g><path d="M60.7,121.5L60.7,121.5c-4,0-7.8-1.6-10.6-4.4L4.4,71.4c-5.9-5.9-5.9-15.4,0-21.2c5.9-5.9,15.4-5.9,21.2,0l35.1,35.1l80.9-80.9c5.9-5.9,15.4-5.9,21.2,0c5.9,5.9,5.9,15.4,0,21.2l-91.5,91.5C68.5,119.9,64.7,121.5,60.7,121.5z"/></g></svg>
                            </div>
                            <div class="button-submit__error">
                                <svg class="svg-icon" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:a="http://ns.adobe.com/AdobeSVGViewerExtensions/3.0/" x="0px" y="0px" width="47.9px" height="47.9px" viewBox="0 0 47.9 47.9" enable-background="new 0 0 47.9 47.9" xml:space="preserve"><defs></defs><path fill="#231F20" d="M31.7,23.9L46.3,9.4c2.1-2.1,2.1-5.6,0-7.8c-2.1-2.1-5.6-2.1-7.8,0L23.9,16.2L9.4,1.6c-2.1-2.1-5.6-2.1-7.8,0c-2.1,2.1-2.1,5.6,0,7.8l14.6,14.6L1.6,38.5c-2.1,2.1-2.1,5.6,0,7.8c1.1,1.1,2.5,1.6,3.9,1.6s2.8-0.5,3.9-1.6l14.6-14.6l14.6,14.6c1.1,1.1,2.5,1.6,3.9,1.6s2.8-0.5,3.9-1.6c2.1-2.1,2.1-5.6,0-7.8L31.7,23.9z"/></svg>
                            </div>
                        </button>
                    </div>
                    <ul class="form__errors workshop-errors"></ul>
                    <ul class="form__success workshop-success">
                        <li>You workshop has been successfully submitted. Once it has been approved, it will be listed on the homepage and you will be able to install it via the workshop manager.</li>
                    </ul>
                </form>
            </div>
        </div>
    </div>
</section>