<?= $this->fetch('includes/submit-header.phtml') ?>

<section class="site-body">
    <div class="container">
        <div class="ws-submit">
            <div class="ws-submit__content">
                <h2>Built a workshop?</h2>
                <p>Through this form you can submit your workshop for approval, once approved your workshop will appear on the website and be installable by the workshop manager. To learn how to build a workshop, head over to the <a href="/docs">docs</a> or jump on to <a href="<?= $links['slack'] ?>">slack</a> for any help!</p>

                <h2>What does submitting mean?</h2>
                <p>Submitting your workshop sends a request for approval to the PHP School team. Once approved, your workshop will appear on the homepage and will be installable via the workshop manager.</p>

                <h2>What is the approval process?</h2>
                <p>We are just making sure the quality is high and there is not lots of duplicated content across the workshops. We want PHP School to lead the way in quality education material.</p>
            </div>
            <div class="ws-submit__form">
                <form id="ws-submit-form" action="/submit" method="get" class="form" _lpchecked="1">
                    <div class="field">
                        <label for="form1-text">Email Address</label>
                        <div class="input-box">
                            <input name="email" id="email" class="input-text ws-submit__input email" type="text" placeholder="myname@example.com" required="">
                            <ul class="form__errors email-errors"></ul>
                        </div>
                    </div>
                    <div class="field">
                        <label for="form1-password">Workshop Name</label>
                        <div class="input-box">
                            <input name="name" id="name" class="input-text ws-submit__input name" type="text" placeholder="Learn You PHP!" required="">
                            <ul class="form__errors name-errors"></ul>
                        </div>
                    </div>
                    <div class="field">
                        <label for="form1-email">GitHub Repository URL</label>
                        <div class="input-box">
                            <input name="github-url" id="github-url" class="input-text ws-submit__input gh" type="text" name="github-url" placeholder="https://github.com/php-school/learn-you-php" required="">
                            <ul class="form__errors gh-errors"></ul>
                        </div>
                    </div>
                    <div class="form__actions">
                        <button type="submit" class="button button--bold button-submit"><span>Submit</span>
                            <div class="loader-wapper">
                                <div class="loader"></div>
                            </div>
                            <div class="button-submit__success"><?= $this->fetch('includes/icon.phtml', ['name' => "tick"]) ?></div>
                            <div class="button-submit__error"><?= $this->fetch('includes/icon.phtml', ['name' => "cross"]) ?></div>
                        </button>
                    </div>
                    <ul class="form__errors workshop-errors"></ul>
                    <ul class="form__success workshop-success">
                        <li>You workshop has been successfully submitted. Once it has been approved, it will be listed on the homepage and you will be able to install it via the workshop manager.</li>
                    </ul>
                </form>
            </div>
        </div>
    </div>
</section>