<p>Welcome to the PHP School documentation - The documentation is spit up in to several sections:</p>

<h3><a href="/docs/tutorial">Workshop Tutorial</a></h3>
<p>Learn how to setup and build a workshop step by step!</p>

<h3><a href="/docs/reference">Reference Documentation</a></h3>
<p>Learn about the individual components of the workshop such as the available checks, exercise types, solutions, services and so on.</p>

<br>
<br>
<hr>

<h3><a href="/submit">Already built a workshop?</a></h3>
<p>Go forth and <a href="/submit">submit it to us</a>!</p>