<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Active Workshop</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="/admin/regenerate">Regenerate Feed</a></li>
                        </ul>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content" style="display: block;">
                <div class="table-responsive">
                    <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Code</th>
                            <th>Display Name</th>
                            <th>Repo</th>
                            <th>Submitter E-mail</th>
                            <th>Status</th>
                            <th>Type</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($workshops as $i => $workshop): ?>
                            <tr>
                                <th scope="row"><?= $i + 1 ?></th>
                                <td><a href="/admin/workshop/view/<?= $workshop->getId() ?>"><?= $workshop->getCode(); ?></a></td>
                                <td><?= $workshop->getDisplayName(); ?></td>
                                <td>
                                    <a target="_blank" href="<?= $workshop->getRepoUrl(); ?>">
                                        <?= $workshop->getRepoUrl(); ?>
                                    </a>
                                </td>
                                <td><?= $workshop->getSubmitterEmail() ?></td>
                                <td>
                                    <span class="label label-<?= $workshop->isApproved() ? 'success' : 'danger' ?>">
                                        <?= $workshop->isApproved() ? 'Approved' : 'Not-approved' ?>
                                    </span>
                                </td>
                                <td>
                                    <span class="label label-<?= $workshop->isCore() ? 'success' : 'info' ?>">
                                        <?= $workshop->getTypeName() ?>
                                    </span>
                                </td>
                                <td>
                                    <ul class="nav navbar-right panel_toolbox" style="min-width: 0px;">
                                        <li class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                            <ul class="dropdown-menu" role="menu">
                                                <?php if (!$workshop->isCore()): ?>
                                                    <li><a href="/admin/workshop/promote/<?= $workshop->getId() ?>">Promote to core</a></li>
                                                <?php else: ?>
                                                    <li><a href="#">No actions</a></li>
                                                <?php endif; ?>
                                            </ul>
                                        </li>
                                    </ul>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">

            <div class="x_title">
                <h2>Last 30 day download stats for workshops</h2>
                <div class="clearfix"></div>
            </div>


            <div class="x_content">
                <div >
                    <canvas id="myChart" style="display: block; width: 100%;"></canvas>
                </div>
            </div>

        </div>
        <script>
            document.addEventListener("DOMContentLoaded", function(event) {
                var randomColorFactor = function () {
                    return Math.round(Math.random() * 255);
                };
                var randomColor = function (opacity) {
                    return 'rgba(' + randomColorFactor() + ',' + randomColorFactor() + ',' + randomColorFactor() + ',' + (opacity || '.3') + ')';
                };

                var data = <?= json_encode($workshopInstalls['installs']) ?>;
                datasets = data.map(function (workshop) {
                    return {
                        label: '# of Downloads for ' + workshop.name,
                        data: workshop.installs,
                        fill: false,
                        tension: 0.5,
                        borderWidth: 5
                    };
                });

                var ctx = document.getElementById("myChart");
                var config = {
                    type: 'line',
                    data: {
                        labels: <?= json_encode($workshopInstalls['dates']) ?>,
                        datasets: datasets
                    },
                    options: {
                        scales: {
                            yAxes: [{
                                ticks: {
                                    beginAtZero: true
                                }
                            }]
                        },
                        hover: {
                            mode: 'dataset'
                        },
                    }
                };

                $.each(config.data.datasets, function (i, dataset) {
                    dataset.borderColor = randomColor(0.4);
                    dataset.backgroundColor = randomColor(0.5);
                    dataset.pointBorderColor = randomColor(0.7);
                    dataset.pointBackgroundColor = randomColor(0.5);
                    dataset.pointBorderWidth = 1;
                });

                var myChart = new Chart(ctx, config);
            });
        </script>
    </div>
</div>
