<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Active Workshop</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="/admin/regenerate">Regenerate Feed</a></li>
                        </ul>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content" style="display: block;">
                <div class="table-responsive">
                    <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Display Name</th>
                            <th>Description</th>
                            <th>Repo</th>
                            <th>Submitter E-mail</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($workshops as $i => $workshop): ?>
                            <tr>
                                <th scope="row"><?= $i + 1 ?></th>
                                <td><a href="/admin/workshop/view/<?= $workshop->getId() ?>"><?= $workshop->getName(); ?></a></td>
                                <td><?= $workshop->getDisplayName(); ?></td>
                                <td><?= $workshop->getDescription(); ?></td>
                                <td>
                                    <a target="_blank" href="<?= $workshop->getRepoUrl(); ?>">
                                        <?= $workshop->getRepoUrl(); ?>
                                    </a>
                                </td>
                                <td></td>
                                <td>
                                    <span class="label label-<?= $workshop->isApproved() ? 'success' : 'danger' ?>">
                                        <?= $workshop->isApproved() ? 'Approved' : 'Not-approved' ?>
                                    </span>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                </div>
            </div>
        </div>
    </div>
</div>
