<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Workshop Submissions <small>Check them out and approve them!</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content" style="display: block;">
                <div class="table-responsive">
                    <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Code</th>
                            <th>Display Name</th>
                            <th>Description</th>
                            <th>Repo</th>
                            <th>Submitter E-mail</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($workshops as $i => $workshop): ?>
                            <tr>
                                <th scope="row"><?= $i + 1 ?></th>
                                <td><?= $workshop->getCode(); ?></td>
                                <td><?= $workshop->getDisplayName(); ?></td>
                                <td><?= $workshop->getDescription(); ?></td>
                                <td>
                                    <a target="_blank" href="<?= $workshop->getRepoUrl(); ?>">
                                        <?= $workshop->getRepoUrl(); ?>
                                    </a>
                                </td>
                                <td><?= $workshop->getSubmitterEmail() ?></td>
                                <td><a class="btn btn-success btn-sm" href="/admin/workshop/approve/<?= $workshop->getId() ?>">Approve</a></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                </div>
            </div>
        </div>
    </div>
</div>
