<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="dashboard_graph">

            <div class="row x_title">
                <div class="col-md-12">
                    <h3>Last 30 day download stats for workshop: <?= $workshop->getDisplayName() ?></h3>
                </div>
            </div>

            <div class="col-md-12 col-sm-12 col-xs-12">
                <div style="width: 100%;">
                    <canvas id="myChart" style="display: block; width: 100%;"></canvas>
                </div>
            </div>

            <div class="clearfix"></div>
        </div>
        <?php

        $end = new DateTimeImmutable();
        $begin  = $end->sub(new \DateInterval("P30D"));
        $end = $end->modify('+1 day');

        $interval = new DateInterval('P1D');
        $dateRange = new DatePeriod($begin, $interval ,$end);

        $dates = [];
        $data = [];
        foreach ($dateRange as $i => $date) {
            $dates[] = $date->format('d M');
            $data[$i] = 0;
            foreach ($installs as $install) {
                if ($install->getDateTime()->format('d-m-Y') === $date->format('d-m-Y')) {
                    $data[$i]++;
                }
            }
        }
        ?>
        <script>


            document.addEventListener("DOMContentLoaded", function(event) {
                var randomColorFactor = function () {
                    return Math.round(Math.random() * 255);
                };
                var randomColor = function (opacity) {
                    return 'rgba(' + randomColorFactor() + ',' + randomColorFactor() + ',' + randomColorFactor() + ',' + (opacity || '.3') + ')';
                };

                var ctx = document.getElementById("myChart");
                var config = {
                    type: 'line',
                    data: {
                        labels: <?= json_encode($dates) ?>,
                        datasets: [{
                            label: '# of Downloads',
                            data: <?= json_encode($data) ?>,
                            fill: true,
                            tension: 0.5,
                            borderWidth: 5
                        }]
                    },
                    options: {
                        scales: {
                            yAxes: [{
                                ticks: {
                                    beginAtZero: true
                                }
                            }]
                        },
                        hover: {
                            mode: 'dataset'
                        },
                    }
                };

                $.each(config.data.datasets, function (i, dataset) {
                    dataset.borderColor = randomColor(0.4);
                    dataset.backgroundColor = randomColor(0.5);
                    dataset.pointBorderColor = randomColor(0.7);
                    dataset.pointBackgroundColor = randomColor(0.5);
                    dataset.pointBorderWidth = 1;
                });

                var myChart = new Chart(ctx, config);
            });
        </script>
    </div>
</div>
