name: PhpSchool.io

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, online ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Eslint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install NPM Dependencies
        run: npm ci --no-audit --no-fund --prefer-offline

      - name: Prettier
        run: npm run prettier:ci
